### PR TITLE
lots of linting fixes, import/export, working for me

### PR DESCRIPTION
**Pull request by zeroasterisk**

### CODE REVIEW

**Comment by kndt84** [comment]
Thx for sending a pull request, however, it doesn't work in Node.js environment due to module loader. In specific, dist/apigClient.js includes from/import syntax and it causes an error. Could you transpile the ES6 code to a CommonJS one with Babel?

**Comment by zeroasterisk** [comment]
It is transpiling, but apparently not to the correct version/stage... mybad.

I switched to `es2015+stage-0` - think that's ok?

**Comment by zeroasterisk** [comment]
Also - added a super-basic test to see if the client can be created --- TODO extend with other tests, of the client and perhaps unit tests for the lib too...?

**Comment by kndt84** [comment]
@ava/babel-preset-stage-4 is not found in devDependencies and it causes an error.

**Comment by zeroasterisk** [comment]
```
rm -rf node_modules
npm i
npm run lint
npm run transpile
npm test
```
^ all working for me

**Comment by kndt84** [comment]
I checked the commands, however, it seems that both babel-register and babel-polyfill are needed in devDependencies.

**Comment by zeroasterisk** [comment]
I wonder why I keep not having these same problems.  

thanks for reviewing and helping me get it finished up - sorry for so much back and forth.

**Comment by kndt84** [comment]
ava@0.19.1 does not work, but I will correct lately.

**Pull request merged**
