### PR TITLE
code update

### PR DESCRIPTION
**Pull request by ngoyal16**

### CODE REVIEW

**Comment by kndt84** [comment]
Please add the description which explains the reason why you update the code.

**Comment by ngoyal16** [comment]
code redundancy was there I remove the redundant code by combining and merging...

**Comment by zeroasterisk** [comment]
Possibly problem - before this chance we supported an `undefined` - now we don't.

Possible solution:
`apigClientFactory.newClient = (config = {}) => {`

**Comment by ngoyal16** [comment]
I have fixed the undefined problem as well

**Pull request merged**
