### PR TITLE
New `systemClockOffset` option

### PR DESCRIPTION
**Pull request by adambiggs**
Added a new `systemClockOffset` option to mirror the one in the AWS SDK.

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#systemClockOffset-property

### CODE REVIEW

**Comment by kndt84** [comment]
I understand the offset option and it would be good, but dist/* files are generated automatically by babel. You only need to modify src/* file. Pls update pull request not to modify dist/* files. Thx!

**Comment by adambiggs** [comment]
@kndt84 sounds good. `dist/*` should probably be added to `.gitignore` then right?

**Comment by adambiggs** [comment]
I updated `.gitignore` to ignore `dist/*` files, and added an empty `.npmignore` file so that those files will still be published to the npm package. I think that's pretty standard practice for npm modules. Let me know what you think.

**Comment by kndt84** [comment]
Thx! It's a nice update.

**Pull request merged**
