### PR TITLE
fix: Retry fails if retry condition is not explicitly defined.

### PR DESCRIPTION
**Pull request by willvincent**
If retryCondition is _not_ defined in the aws api client config, or is defined incorrectly (not a function), it should fallback to use the default axiosRetry retry condition of `isNetworkOrIdempotentRequestError`

Without this, on first attempt of retry it will error out with a "retryCondition is not a function" error... The end result is the client continues to work as if retry config were disabled, but the error can be difficult to detect leading one to believe everything is in fact operating as expected.

### CODE REVIEW

**Comment by willvincent** [comment]
This also fixes the still broken signing issue(s) when retry is enabled.

**Comment by lsanders** [comment]
@kndt84  - This is pretty similar to #96 (sorry I had overlooked this code path - thanks @willvincent for the PR). Do you think you'd merge/release soon? If that's not likely, we'll probably merge into our fork.

**Comment by willvincent** [comment]
Yea, I'm running off my fork presently, otherwise it doesn't work at all with signing & retry enabled...

I never noticed before because I never actually upgraded the version my production code was running previously, so for the past year or whatever I've been operating under the assumption things were retrying when in reality nothing was because the version I had didn't have any retry logic available! 🤣

A merge and release would be desirable, @kndt84

**Comment by kyleerickson** [comment]
@kndt84 and team - any chance we can get this merged in?

**Comment by lsanders** [comment]
@kyleerickson - until it's merged, you can depend on this branch directly, or if you prefer, you can use our fork:

`npm i @adastradev/aws-api-gateway-client`

**Pull request merged**
